name = "llms"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
mist = ">= 4.0.4 and < 5.0.0"
wisp = ">= 1.5.1 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
dotenv_gleam = ">= 1.0.7 and < 2.0.0"
